app_home:
    path: /
    controller: App\Controller\HomeController::index
app_home_flash:
    path: /flash
    controller: App\Controller\HomeController::flashMessage

app_post:
    path: /post
    controller: App\Controller\PostController::index
app_post_new:
    path: /post/new
    controller: App\Controller\PostController::create
app_post_id:
    path: /post/{id}
    controller: App\Controller\PostController::show

app_user_create:
    path: /user/create
    controller: App\Controller\UserController::create
app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show

#app_login:
#    path: /login
#    controller: App\Controller\AuthController::login
