app_home:
    path: /
    controller: App\Controller\HomeController::index
app_home_flash:
    path: /flash
    controller: App\Controller\HomeController::flashMessage

app_post:
    path: /post
    controller: App\Controller\PostController::index
app_post_new:
    path: /post/new
    controller: App\Controller\PostController::create
app_post_id:
    path: /post/{id}
    controller: App\Controller\PostController::show

app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show
app_user_edit:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit

app_register:
    path: /signup
    controller: App\Controller\RegistrationController::register
app_login:
    path: /login
    controller: App\Controller\AuthController::login
app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

app_admin:
    path: /admin
    controller: App\Controller\AdminController::index
app_admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::usersList
app_admin_user:
    path: /admin/user/{id}
    controller: App\Controller\UserController::edit